### ISSUE TITLE
Restricted systems

### ISSUE THREAD

**Issue by LEK85** [numeralbank/barlowpacific#3]
Hi,
I have a question on restricted numeral systems @barlowrussell 

We need to know the reliability of the data on restricted systems: if a language has only numerals for 1-10, is it a restricted system or the wordlist just stopped there? Is there any way to know this? (e.g. metadata on whether a system is/might be restricted).

We would like to disentangle which data is known and which unknown, for running our analyses. For the languages we have no data, we can try to go to the sources and complete these gaps (at least for the restricted systems which don’t seem to be so many).

Thanks!

Ezequiel

**Comment by barlowrussell** [comment]
Hey, Ezequiel! What definition are you using for "restricted"? If you're asking whether there are languages that have conventionalized ways of referring to every integer from 1 to 10, but *not* to 11, I'd be very surprised if there are many (any?) languages like this. So, yeah, I'd bet that >95% of the entries numeralbank doculects that have data for only 1-10 stop at 10 because the wordlist ends there. Some of these may still be considered "restricted", though, depending on your definition (e.g., if 10 is formed as 2+2+2+2+2).

**Comment by LEK85** [comment]
Thanks! Yes, that's exactly what I mean: conventionalized way of referring to 1 to N but not to N+1. Understood for N=10, but is there any case with a documented maximum N, or in all cases in the database the coding ends with the wordlist, and it could in principle be continued?

**Comment by barlowrussell** [comment]
That depends in part on your requirements for conventionalization. In principle anything could be continued (I'd have a hard time imagining that a speaker could produce '2+2+2+2+2' for '10' but *not* '2+2+2+2+2+2' for '12'). But I doubt that it's ever particularly conventional to make either of those utterances. Eugene Chan's site sometimes contains metadata pertaining to restrictedness (e.g., https://lingweb.eva.mpg.de/channumerals/Yanyuwa.htm ). I don't think this has been transferred to numeralbank though. Numerals of the Pacific includes this information when it's in the original source (e.g., https://numerals.clld.org/languages/barlowpacific-beri1254-2 ), but most sources don't say one way or the other if the system "ends". This particular source is a good example of the difficulties with conventionalization, since other sources for [beri1254] document higher numerals.

**Comment by LEK85** [comment]
Great, thanks a lot!
